'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
'''

lista = [1, 2]                         #Resolvi usar uma lista para guardar os valores iniciais.
i = 1
while lista[i] < 4000000:
    lista.append(lista[i-1]+lista[i])  # Aqui fica definido o crescimento da lista.
    i += 1
del lista[-1]                          # Estou tirando o ultimo termo, pois ele é maior que 4 000 000
soma = 0                               # Definindo a variável soma
for i in lista:
    if (i%2 == 0):                     # condição de ser divisível por 2
        soma = soma + i
print("A sequencia tem", len(lista), "termos.")
print("Seus termos são\n", lista)
print("E sua soma é", soma)